[package]
name = "tangle_test_support"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Test fixtures and utilities for Tangle"

[dependencies]
pocket-types = { git = "https://github.com/triesap/pocket", rev = "d24cf774a31978cf83d2b7289a618d3959bcc645" }
serde_json = "1"
tangle_crypto = { path = "../tangle_crypto" }
tangle_groups = { path = "../tangle_groups" }
tangle_protocol = { path = "../tangle_protocol" }

[lints]
workspace = true
